
Window("Calculator").WinButton("Button").Click @@ hightlight id_;_3802072_;_script infofile_;_ZIP::ssf7.xml_;_
Window("Calculator").WinButton("Button_7").Click @@ hightlight id_;_2032336_;_script infofile_;_ZIP::ssf8.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_4849910_;_script infofile_;_ZIP::ssf9.xml_;_
Window("Calculator").WinButton("Button_5").Click @@ hightlight id_;_2032630_;_script infofile_;_ZIP::ssf10.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_852530_;_script infofile_;_ZIP::ssf11.xml_;_
Window("Calculator").WinButton("Button_9").Click @@ hightlight id_;_3540342_;_script infofile_;_ZIP::ssf12.xml_;_
Window("Calculator").WinButton("Button_7").Click @@ hightlight id_;_2032336_;_script infofile_;_ZIP::ssf13.xml_;_
Window("Calculator").WinButton("Button_5").Click @@ hightlight id_;_2032630_;_script infofile_;_ZIP::ssf14.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_852530_;_script infofile_;_ZIP::ssf15.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_4849910_;_script infofile_;_ZIP::ssf16.xml_;_
Window("Calculator").WinButton("Button_5").Click @@ hightlight id_;_2032630_;_script infofile_;_ZIP::ssf17.xml_;_
Window("Calculator").WinButton("Button_7").Click @@ hightlight id_;_2032336_;_script infofile_;_ZIP::ssf18.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_852530_;_script infofile_;_ZIP::ssf19.xml_;_
Window("Calculator").WinButton("Button_10").Click @@ hightlight id_;_4194702_;_script infofile_;_ZIP::ssf20.xml_;_
Window("Calculator").WinButton("Button_5").Click @@ hightlight id_;_2032630_;_script infofile_;_ZIP::ssf21.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_852530_;_script infofile_;_ZIP::ssf22.xml_;_
Window("Calculator").WinButton("Button_11").Click @@ hightlight id_;_3277978_;_script infofile_;_ZIP::ssf23.xml_;_
Window("Calculator").WinButton("Button_12").Click @@ hightlight id_;_2818682_;_script infofile_;_ZIP::ssf24.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_852530_;_script infofile_;_ZIP::ssf25.xml_;_
Window("Calculator").WinButton("Button_13").Click @@ hightlight id_;_2097782_;_script infofile_;_ZIP::ssf26.xml_;_
Window("Calculator").WinButton("Button_3").Click @@ hightlight id_;_2294676_;_script infofile_;_ZIP::ssf27.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_852530_;_script infofile_;_ZIP::ssf28.xml_;_
Window("Calculator").WinButton("Button_14").Click @@ hightlight id_;_1638974_;_script infofile_;_ZIP::ssf29.xml_;_
Window("Calculator").WinButton("Button_15").Click @@ hightlight id_;_4129016_;_script infofile_;_ZIP::ssf30.xml_;_
Window("Calculator").WinButton("Button_10").Click @@ hightlight id_;_4194702_;_script infofile_;_ZIP::ssf31.xml_;_
Window("Calculator").WinButton("Button_5").Click @@ hightlight id_;_2032630_;_script infofile_;_ZIP::ssf32.xml_;_
Window("Calculator").WinButton("Button_12").Click @@ hightlight id_;_2818682_;_script infofile_;_ZIP::ssf33.xml_;_
Window("Calculator").WinButton("Button_8").Click @@ hightlight id_;_4849910_;_script infofile_;_ZIP::ssf34.xml_;_
Window("Calculator").WinButton("Button_5").Click @@ hightlight id_;_2032630_;_script infofile_;_ZIP::ssf35.xml_;_
Window("Calculator").WinButton("Button_6").Click @@ hightlight id_;_852530_;_script infofile_;_ZIP::ssf36.xml_;_
Window("Calculator").WinButton("Button_16").Click @@ hightlight id_;_4457036_;_script infofile_;_ZIP::ssf37.xml_;_
Window("Calculator").Close
